# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      
      - run: yarn
      - run: yarn lint
      - run: yarn pretty
  build:
    needs: ['test']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          registry: core.harbor.cluster.jetop.com
          username: ${{secrets.HARBOR_USERNAME}}
          password: ${{secrets.HARBOR_PASSWORD}}
          
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.4.0
        with:
          tags: core.harbor.cluster.jetop.com/bots/circolo-del-frontend:${{github.sha}}
          push: true

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v1
        with:
          version: v1.20.2
      
      - name: Set up Kubeconfig
        run: |
          mkdir ~/.kube
          echo "${{secrets.KUBECONFIG}}" > ~/.kube/config
          kubectl -n bots set image deployment/circolo-del-frontend circolo-del-frontend=core.harbor.cluster.jetop.com/bots/circolo-del-frontend:${{github.sha}}
